/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BgVideo: typeof import('./../components/Effects/BgVideo.vue')['default']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    LogAndSign: typeof import('./../components/Home/Navbar/components/LogAndSign/index.vue')['default']
    LogIn: typeof import('./../components/Home/Navbar/components/LogAndSign/components/LogIn.vue')['default']
    Logo: typeof import('./../components/Common/Logo.vue')['default']
    LottieAnimation: typeof import('./../components/Common/LottieAnimation.vue')['default']
    MiddelAnimation: typeof import('./../components/Home/Navbar/components/LogAndSign/components/MiddelAnimation.vue')['default']
    Navbar: typeof import('./../components/Home/Navbar/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./../components/Home/Navbar/components/Search/index.vue')['default']
    SignUp: typeof import('./../components/Home/Navbar/components/LogAndSign/components/SignUp.vue')['default']
    Transform: typeof import('./../components/Common/Transform.vue')['default']
    UserIcon: typeof import('./../components/Home/Navbar/components/UserIcon/index.vue')['default']
  }
}
