/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    A: typeof import('./../components/Home/MainBody/components/a.vue')['default']
    B: typeof import('./../components/Home/MainBody/components/b.vue')['default']
    BgVideo: typeof import('./../components/Effects/BgVideo.vue')['default']
    Control: typeof import('./../components/TEMP/TOPIC/Control.vue')['default']
    Drawer: typeof import('./../components/AddTopic/EditArea/components/Drawer.vue')['default']
    EditArea: typeof import('./../components/AddTopic/EditArea/index.vue')['default']
    Editor: typeof import('./../components/AddTopic/EditArea/components/Editor.vue')['default']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    FileItem: typeof import('./../components/AddTopic/EditArea/components/DrawerComponents/FileItem.vue')['default']
    LogAndSign: typeof import('./../components/Home/Navbar/components/LogAndSign/index.vue')['default']
    LogIn: typeof import('./../components/Home/Navbar/components/LogAndSign/components/LogIn.vue')['default']
    Logo: typeof import('./../components/Common/Logo.vue')['default']
    LottieAnimation: typeof import('./../components/Common/LottieAnimation.vue')['default']
    MainBody: typeof import('./../components/Home/MainBody/index.vue')['default']
    Navbar: typeof import('./../components/Home/Navbar/index.vue')['default']
    NavBar: typeof import('./../components/AddTopic/NavBar/index.vue')['default']
    Pagination: typeof import('./../components/TEMP/TOPIC/Pagination.vue')['default']
    PartOne: typeof import('./../components/Home/MainBody/components/partOne.vue')['default']
    Preview: typeof import('./../components/TEMP/TOPIC/TopicComponents/Preview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./../components/TEMP/Search/index.vue')['default']
    SignUp: typeof import('./../components/Home/Navbar/components/LogAndSign/components/SignUp.vue')['default']
    Submit: typeof import('./../components/AddTopic/NavBar/components/Submit.vue')['default']
    Title: typeof import('./../components/AddTopic/EditArea/components/DrawerComponents/Title.vue')['default']
    TitleInput: typeof import('./../components/AddTopic/NavBar/components/TitleInput.vue')['default']
    Topic: typeof import('./../components/TEMP/TOPIC/Topic.vue')['default']
    Transform: typeof import('./../components/Common/Transform.vue')['default']
    UploadingAnimation: typeof import('./../components/Common/UploadingAnimation.vue')['default']
    UploadState: typeof import('./../components/AddTopic/EditArea/components/DrawerComponents/FileItemComponents/UploadState.vue')['default']
    UserIcon: typeof import('./../components/Home/Navbar/components/UserIcon/index.vue')['default']
  }
}
